version: "3"
services:
  jfrog-jcr:
    user: root
    image: registry.cn-beijing.aliyuncs.com/meowbite/jfrog-jcr
    ports:
      - 8081:8081
    volumes:
      - /data/jfrog/artifactory:/var/opt/jfrog/artifactory
